name: MAPS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - tifffile
  - einops
  - numba
  - scikit-image
  - matplotlib
  - tqdm
  - pytorch
  - torchvision
  - tensorboard
  - torchaudio
  - pytorch-lightning
  - pytorch-cuda=12.1
  - pip
  - pip:
  
